language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: graphene-blockchain/graphene-ui
        - ORGANIZATION_REPO: graphene-blockchain/gph.ai
        - WALLET_REPO: graphene-blockchain/wallet.gph.ai
        - CXX=g++-4.8
        - secure:
              NYt+/r5/JYV7lTVF1Oz2nqh99sCnA+QBauQPFZsLcMJKKpqFj5BJIZ1XjjRbhJ8G9rhYcxr9P042bNT365qf+L9wPJzGpv5LEsQAeThmnH+V4V8Jv3Ey0faAtWHekJ7vgvf/+G9+oLWkusCSjfmQHAcJzdHaohpsObL0NIuF8XQX+OB8idkYDL+PxFQOF7B2hb9e7ogdHQZ4m8+MzcKSe6T+/CRoLWdM9eTCbQpm2xOrrPz37HPQfThJlvpktZj3b2EH1tz1y88vZYZG44R6UD56RXhXFViloJhQGPU0iX0GAdo1ETwMUHB99j81CSImzt+eCRMW43WBg9r456Tc5dLzvTaQavgZ3OW3Tv617FqNVZREa/KAbTCUGml6jYEmApCBh5evNAWDffwuhOZQwJ0MkdWuZo5nCc8d7hDGkJC3f7jEj14vQCUxLGwkfIwjM2m45nbhTxLY6syGNtIEsn0aD2CxYwzYyGKOPLcDWsxBASNyG5+UWb/a0LhZZuhUn+nBfqU07itlO7cVFANTiMuh9Ob+XluKZKVp7tQaKDT95qtF4iW/u+ZAel5hdxNDl79UtQbZGtlx5OD1fgrgNzqgR6LHWRzq5Y364os7ZnqnSjqjuGStue27TiBV+2Woap3qKpvRCKgpX0JigfHSGvr1hvR1Ajh188ckHEnOiFc=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
#after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure:
            fFDBhIKpj7XIYFdfmxhPS8sZEEwk3EsWnzC2NFqCZgK3/OgRd8KZ2+SMG9j8AEsPTMsHhXzbHVnnQEw6zcnVm6IZ5vQKwTj5P5ls6CeNzsBmnpE/tx0KHKoSzwq2K5EU7qmbTbLfd7dICwl/AsxMQm9OUG6Oeb4UZTH4gIMRP2bJFiFPm8qw5tW71a1OjAnt0eSqI3PXflNZPgQg56VuAMkK0qsq86vkyu2YxygyzbEheHPQz4QbBDgKC6DTsLpNdsrfuT46V0IxG/WIG7a94y1wws+3JFH+Wwh8lS7g6FLOA3V5wAhG2Ye7b5it7WHoMBZm2goaJwGvNWKPopbCnP74B8zWCs8kyuBRuKBs3xFjip0O8fZ0VKMMSfdu11fI95PR+GFU/FNJeKpElYm/e9E/GmkNVfwnyIKJ0RYR9dTQme5013exMvkbNA9+adPRBYWitzJaXXWZcyaYH+6jyM0X8khfVFPDjHk6EvDfGtC2Lh9IiI5QIWhnKGMR19fU+C5ebq0ARJv6sY1Z5mwbBfvTmeHlqceTmkRo4iW75T+o0I8E8tRk1jQLew1CEdmgKf4pcgGaQ8KCSbSfSCMV7vf+gwYyib0NnIBok1J2u0EqzvECy/VEkfmtdgDrd2CIK7Q57F7TTMMsEhXODHq/aOva7Y+r82f6SpxMpjmJSe8=
    file_glob: true
    file:
        - build/binaries/Graphene*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: graphene-blockchain/graphene-ui
        tags: true
