language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: graphene-blockchain/graphene-ui
        - ORGANIZATION_REPO: graphene-blockchain/gph.ai
        - WALLET_REPO: graphene-blockchain/wallet.gph.ai
        - CXX=g++-4.8
        - secure:
              NYt+/r5/JYV7lTVF1Oz2nqh99sCnA+QBauQPFZsLcMJKKpqFj5BJIZ1XjjRbhJ8G9rhYcxr9P042bNT365qf+L9wPJzGpv5LEsQAeThmnH+V4V8Jv3Ey0faAtWHekJ7vgvf/+G9+oLWkusCSjfmQHAcJzdHaohpsObL0NIuF8XQX+OB8idkYDL+PxFQOF7B2hb9e7ogdHQZ4m8+MzcKSe6T+/CRoLWdM9eTCbQpm2xOrrPz37HPQfThJlvpktZj3b2EH1tz1y88vZYZG44R6UD56RXhXFViloJhQGPU0iX0GAdo1ETwMUHB99j81CSImzt+eCRMW43WBg9r456Tc5dLzvTaQavgZ3OW3Tv617FqNVZREa/KAbTCUGml6jYEmApCBh5evNAWDffwuhOZQwJ0MkdWuZo5nCc8d7hDGkJC3f7jEj14vQCUxLGwkfIwjM2m45nbhTxLY6syGNtIEsn0aD2CxYwzYyGKOPLcDWsxBASNyG5+UWb/a0LhZZuhUn+nBfqU07itlO7cVFANTiMuh9Ob+XluKZKVp7tQaKDT95qtF4iW/u+ZAel5hdxNDl79UtQbZGtlx5OD1fgrgNzqgR6LHWRzq5Y364os7ZnqnSjqjuGStue27TiBV+2Woap3qKpvRCKgpX0JigfHSGvr1hvR1Ajh188ckHEnOiFc=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
#after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: "$TRAVIS_TAG"
    name: "$TRAVIS_TAG"
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure:
            WJXIYvyVn5VigQ6gsa8n+PjtDS/E+F9pQouzvJ8NAhUWVgDtEzLGm0jDRg9gsh/zmeB14eiyCrkNYH45FYiTMWDz+8ydzJXeBoWkpwduFWPb1sifRrEuPVUIJ2mDK5UBW4eobQHNda9taUxTBL/VdgZC9KLFuzhwzcFkdkLcBuLZYrmvgziEmJNkQ4/eHc6+n/Hug+dTDIenKcSbw8RH2AZNnGqQOCqEpl8LNMUhl6RczGXC8uu49EMPOON8Km+nlh4frkImbXuXMyudPl3iwTMiZE6xPex5IHS3vbaEbKfJTprNLFnyZyOZnhUCDNatNsRTlrQLMoQgEMYStb9huI/xVdJ6hKZgdVNjiu2ZCYUyxmy2WxBuGc0GBXrojJX4x4U7/+cXohk3DNBMLDcRPQAqWAtre/arIAJLJDi+hVFOmsi03KoWt5F7wduPQe8liaQtLDTa490tdIpJqyUgEKFSEciazkhjd9ggiob2lj+kCfWNe4kPzUogJ+MoenxctIk4aQE/FumnoyjkgOd3bEGMik3B41X6UpRDWqOtkvDRfPw9Pqd9EzjfRiaS7VsjO/ehYflOAdBvpy/PmvYIjdFl/Ij2h3tny74ze4ywVk2xLfN+CQtESHvwVAC1nvcyMvmUj5Wk7eBBnwJeYYGDUhPrB74HMzAFhBgPhq8MfTs=
    file_glob: true
    file:
        - build/binaries/Graphene*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: graphene-blockchain/graphene-ui
        tags: true
