language: node_js
node_js: 9
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: blckchnd/rudex-ui
        - ORGANIZATION_REPO: blckchnd/rudex.org
        - WALLET_REPO: blckchnd/market.rudex.org
        - STAGING_REPO: blckchnd/staging.rudex.org
        - DEVELOP_REPO: blckchnd/dev.rudex.org
        - CXX=g++-4.8
        - secure: "IHljhIJqdoxxVkyD6tsLOc7YUY3e8Rve8OqUocly1ffTEcEbbNHFm1nzfDjWS3WAxMQQhK1g/57/YYZas1KDM5g+XIkGB5H5JUCjd0OKLh+bjwLeCbpBzU3WJSfG9qyq/RI0on4sGCcnttgI6rx6dL9I/FXDlNltRuNX61xV/wJWY/CI/+DtHF1gml8oQtzJ55r+9PtDvVvTyDtX3xraa3vTc5iTtus/PgBZ0jT2uKZzvaoYlxeLyGDFYVMmhJ8TGLfUR4AQE+ioNeUer1TZy/ACMUY072k3nrzVZeJuYWg/8NRtHONdvtGj/9+PM/otHloDtAAtiyeVDaEzHDzKf9fgUfjZxpMi10CoDicX3Xk7MSKUYuFO3PiLgX7tbGJwqcbF+DcPeIJcvjFp++XgT6u3T6dkuEA1aup+GV1L5wCJYO0AgxKZzste2zTMtWYNWLZTtDHcLBp5FkeKoApF30GAXvWgSm/4ZBUHlahSPxRc50Yt7oGkwDjtIfFf+gwerORzt8aeOffGFvrjgE/k9WT6tSa2Z9hNFcD5y2rKm2gT7Ji63EkyJ6DF6kets8tjs3hMaegDj57kjM2sNm/fI28bOmm47M95BmA4DmkPctmaddtZ4zjrEg5n+9ev5Ng4GmJGruVVBNjvlNDbBjCC0WFeibKTwD8df2wxeQpdsYs="
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm install -g npm@6
    - npm ci
script: "./build.sh"
#after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure: "IHljhIJqdoxxVkyD6tsLOc7YUY3e8Rve8OqUocly1ffTEcEbbNHFm1nzfDjWS3WAxMQQhK1g/57/YYZas1KDM5g+XIkGB5H5JUCjd0OKLh+bjwLeCbpBzU3WJSfG9qyq/RI0on4sGCcnttgI6rx6dL9I/FXDlNltRuNX61xV/wJWY/CI/+DtHF1gml8oQtzJ55r+9PtDvVvTyDtX3xraa3vTc5iTtus/PgBZ0jT2uKZzvaoYlxeLyGDFYVMmhJ8TGLfUR4AQE+ioNeUer1TZy/ACMUY072k3nrzVZeJuYWg/8NRtHONdvtGj/9+PM/otHloDtAAtiyeVDaEzHDzKf9fgUfjZxpMi10CoDicX3Xk7MSKUYuFO3PiLgX7tbGJwqcbF+DcPeIJcvjFp++XgT6u3T6dkuEA1aup+GV1L5wCJYO0AgxKZzste2zTMtWYNWLZTtDHcLBp5FkeKoApF30GAXvWgSm/4ZBUHlahSPxRc50Yt7oGkwDjtIfFf+gwerORzt8aeOffGFvrjgE/k9WT6tSa2Z9hNFcD5y2rKm2gT7Ji63EkyJ6DF6kets8tjs3hMaegDj57kjM2sNm/fI28bOmm47M95BmA4DmkPctmaddtZ4zjrEg5n+9ev5Ng4GmJGruVVBNjvlNDbBjCC0WFeibKTwD8df2wxeQpdsYs="
    file_glob: true
    file:
        - build/binaries/RuDEX*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: blckchnd/rudex-ui
        tags: true
