language: node_js
node_js: 9
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: blckchnd/rudex-ui
        - ORGANIZATION_REPO: blckchnd/rudex.org
        - WALLET_REPO: blckchnd/market.rudex.org
        - CXX=g++-4.8
        - secure: gM32UpksN/vPxqBPVgIzs7v0jyE/vCpXA1CBHuL4o4/3ZJ5uf1IZc3h8qThMT+3nJBS5GFi4PS6769uhvsnSMBbgnTrPmXAm/HMrWAzzxklxjsE3a0MmCvG4kcXSwTpe0mjOL+VVHcleGpc7fktIz1ILo9SOxky39NZZagrvSboMgVrzq031zBm1hUl08bs17YJeE6L2nC77ZqQgovtcJTgf/f8D4WUNbsDm/sTJZqLV6jXgQQcpEfbpptS9vZdcpC+uc69adVYekWb2bc6l1Ms6sLickRh9xHkuKuMEcfGh244in0XCxGE87BqAE/lR+hLt4bAsY0QceVLy6bK0k3I0mdGc3hqTO7wrvZTTbQz/ppENFct6b/G99QSyc+cxgMC+vNYVHd6FYdWMnVsFbrgtZEDmIKt7/dusU7y35Es2ypHA3d5fgf+h6/o8bOr5rJ94cgtbwB7D64QQtn6/treECSEAnSSi0yhKXSgfq91QZZ4kearVgxQVSlRWWD0lPKxWvdktvIqZNh4SJUAc0BWm6mmd1/w0zWUJw3is3u7kcB7w5Id88Ci6SgMKvcODsrBJ4uy+JciwEqf2uo0Duv1LyQdZfst9bv4hN1jUh28HWO00urGyjkQT43YURRVa8HcquDgsrE6DZdI/OB9ciMVEVAI1SXfG+2ViGC4eXk8=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm install -g npm@6
    - npm ci
script: "./build.sh"
#after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure: gM32UpksN/vPxqBPVgIzs7v0jyE/vCpXA1CBHuL4o4/3ZJ5uf1IZc3h8qThMT+3nJBS5GFi4PS6769uhvsnSMBbgnTrPmXAm/HMrWAzzxklxjsE3a0MmCvG4kcXSwTpe0mjOL+VVHcleGpc7fktIz1ILo9SOxky39NZZagrvSboMgVrzq031zBm1hUl08bs17YJeE6L2nC77ZqQgovtcJTgf/f8D4WUNbsDm/sTJZqLV6jXgQQcpEfbpptS9vZdcpC+uc69adVYekWb2bc6l1Ms6sLickRh9xHkuKuMEcfGh244in0XCxGE87BqAE/lR+hLt4bAsY0QceVLy6bK0k3I0mdGc3hqTO7wrvZTTbQz/ppENFct6b/G99QSyc+cxgMC+vNYVHd6FYdWMnVsFbrgtZEDmIKt7/dusU7y35Es2ypHA3d5fgf+h6/o8bOr5rJ94cgtbwB7D64QQtn6/treECSEAnSSi0yhKXSgfq91QZZ4kearVgxQVSlRWWD0lPKxWvdktvIqZNh4SJUAc0BWm6mmd1/w0zWUJw3is3u7kcB7w5Id88Ci6SgMKvcODsrBJ4uy+JciwEqf2uo0Duv1LyQdZfst9bv4hN1jUh28HWO00urGyjkQT43YURRVa8HcquDgsrE6DZdI/OB9ciMVEVAI1SXfG+2ViGC4eXk8=
    file_glob: true
    file:
        - build/binaries/RuDEX*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: blckchnd/rudex-ui
        tags: true
